name: "authorised-actor"
description: "Execute a GitHub Action only if the (triggering) actor is authorised to do so."
author: "Arky Asmal"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "briefcase"
  color: "black"
inputs:
  githubToken:
    required: true
    description: "GitHub access token with `repo` scope"
  actor:
    required: false
    description: "Provide the current actor of the workflow. By default it is the value of env.GITHUB_ACTOR"
  authorizedGroups:
    required: false
    description: "Array of groups, i.e owners, admins, etc, managed as a Github Secret to allow only Repository Owners/Admins to change the values"
  authorizedActors:
    required: false
    description: "Array of authorised actors, best managed as a GitHub Secret to allow only Repository Owners/Admins to change the values."
  failSilently:
    required: false
    description: "Whether or not the GitHub action should exit with status code 1 or not."
  failureMessage:
    required: false
    description: "Message to display in the GitHub Action logs when authorised actor check fails."
